# 📊 Análise Exploratória
Este notebook contém a análise exploratória da base escolhida.
Preencha aqui os passos de diagnóstico, limpeza, transformação e análise.

In [63]:
import pandas as pd
import numpy as np

In [64]:
df_viagem = pd.read_csv(
    '2026_Viagem.csv', 
    sep=';', 
    decimal=',', 
    encoding='latin-1', 
    parse_dates=['Período - Data de início', 'Período - Data de fim'],
    dayfirst=True  # <-- data no formato brasileiro (dd/mm/yyyy)
)
df_viagem.head()

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
0,21116870,000073/26,Realizada,SIM,Atraso na solicitação,26000,Ministério da Educação,26436,"Instituto Federal de Educação, Ciência e Tecno...",***.240.140-**,...,FG-0001,FG-0001,2026-02-25,2026-02-25,Venâncio Aires/RS,Motivo da viagem (objeto/assunto a ser tratado...,107.83,0.00,0.0,0.0
1,21126303,000001/26,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26236,Universidade Federal Fluminense,NaN,...,-1,Sem informação,2026-01-25,2026-07-24,Pelotas/RS,Pesquisa com colaboração de professores da Uni...,0.00,0.00,0.0,0.0
2,21342207,000001/26,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.506.203-**,...,Sargento,Sargentos,2026-01-09,2026-01-10,Washington/Estados Unidos da América,A fim de exercer o cargo de Auxiliar da Seção ...,0.00,5927.18,0.0,0.0
3,21343024,000001/26,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26247,Universidade Federal de Santa Maria,***.464.017-**,...,-1,Sem informação,2026-02-28,2026-03-08,Montevidéu/Uruguai,"O docente RODRIGO MARINHO DE SOUZA, SIAPE 1296...",0.00,0.00,0.0,0.0
4,21346664,000002/26,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.526.753-**,...,-1,Sem informação,2026-01-09,2026-01-10,Washington/Estados Unidos da América,Acompanhar militar designado para missão no ex...,0.00,5927.18,0.0,0.0

In [3]:
df_viagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406083 entries, 0 to 406082
Data columns (total 22 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Identificador do processo de viagem  406083 non-null  int64
 1   Número da Proposta (PCDP)            406083 non-null  object
 2   Situação                             406083 non-null  object
 3   Viagem Urgente                       406083 non-null  object
 4   Justificativa Urgência Viagem        405907 non-null  object
 5   Código do órgão superior             406083 non-null  int64
 6   Nome do órgão superior               406083 non-null  object
 7   Código órgão solicitante             406083 non-null  int64
 8   Nome órgão solicitante               406083 non-null  object
 9   CPF viajante                         369197 non-null  object
 10  Nome                                 406083 non-null  object
 11  Cargo                                263822 non-null  object
 12  Função                               406083 non-null  object
 13  Descrição Função                     406078 non-null  object
 14  Período - Data de início             406083 non-null  datetime64[ns]
 15  Período - Data de fim                406083 non-null  datetime64[ns]
 16  Destinos                             406083 non-null  object
 17  Motivo                               406083 non-null  object
 18  Valor diárias                        406083 non-null  float64
 19  Valor passagens                      406083 non-null  float64
 20  Valor devolução                      406083 non-null  float64
 21  Valor outros gastos                  406083 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(13)
memory usage: 68.2+ MB

## Valores "Sem informação" e "Sem informaçã":
- Verificar a relevância das colunas para as perguntas a serem respondidas.  
- Não há necessidade de tratamento, se as colunas e esses valores não forem relevantes para as perguntas da análise.

#### Contagem por coluna de registros com valor "Sem informação"

| Coluna | Registros |
|:---|---:|
| Descrição Função | 191.806 |
| Justificativa Urgência Viagem | 112.914 |
| Destinos | 1.206 |

#### Contagem por coluna de registros com valor "Sem informaçã"

| Coluna | Registros |
|:---|---:|
| Número da Proposta (PCDP) | 677 |

In [ ]:
## Em algumas colunas do dataframe constam os valores "Sem informação" e "Sem informaçã". 
## Verificar a relevância das colunas para as perguntas a serem respondidas. 
## Não há necessidade de tratamento, se as colunas e esses valores não forem relevantes para as perguntas da análise.

contagem1 = (df_viagem == "Sem informação").sum()
contagem1 = contagem1[contagem1 > 0].sort_values(ascending=False)

print('Contagem por coluna de registros com valor "Sem informação":')
print(contagem1)

contagem2 = (df_viagem == "Sem informaçã").sum()
contagem2 = contagem2[contagem2 > 0].sort_values(ascending=False)

print('\nContagem por coluna de registros com valor "Sem informaçã":')
print(contagem2)

Contagem por coluna de registros com valor "Sem informação":
Descrição Função                 191806
Justificativa Urgência Viagem    112914
Destinos                           1206
dtype: int64

Contagem por coluna de registros com valor "Sem informaçã":
Número da Proposta (PCDP)    677
dtype: int64

## Identificação de linhas em que todos os gastos são zero.

- O que fazer com essas linhas com todos gastos zerados?
- Os identificadores do processo de viagem de df_gastos_zerados constam na tabela 2026_Pagamento?
- Se não constarem na tabela pagamentos, essas linhas devem excluídas?

In [ ]:
## O retorno das 5 primeiras linhas de df_viagem mostra que há linhas em que todos os gastos são zero. 

# Criando um filtro para listar somente as colunas de valores monetários:
colunas_gastos = ["Valor diárias", "Valor passagens", "Valor devolução", "Valor outros gastos"]

#Filtrando as linhas onde todos os valores de gastos são zero:
df_gastos_zerados = df_viagem[df_viagem[colunas_gastos].eq(0).all(axis=1)]
print(f'Quantidade de linhas e colunas onde todos os valores de gastos são zero: {df_gastos_zerados.shape[0]} linhas e {df_gastos_zerados.shape[1]} colunas \n')

Quantidade de linhas e colunas onde todos os valores de gastos são zero: 24293 linhas e 22 colunas

In [11]:
df_gastos_zerados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24293 entries, 1 to 405590
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Identificador do processo de viagem  24293 non-null  int64
 1   Número da Proposta (PCDP)            24293 non-null  object
 2   Situação                             24293 non-null  object
 3   Viagem Urgente                       24293 non-null  object
 4   Justificativa Urgência Viagem        24293 non-null  object
 5   Código do órgão superior             24293 non-null  int64
 6   Nome do órgão superior               24293 non-null  object
 7   Código órgão solicitante             24293 non-null  int64
 8   Nome órgão solicitante               24293 non-null  object
 9   CPF viajante                         22516 non-null  object
 10  Nome                                 24293 non-null  object
 11  Cargo                                16658 non-null  object
 12  Função                               24293 non-null  object
 13  Descrição Função                     24292 non-null  object
 14  Período - Data de início             24293 non-null  datetime64[ns]
 15  Período - Data de fim                24293 non-null  datetime64[ns]
 16  Destinos                             24293 non-null  object
 17  Motivo                               24293 non-null  object
 18  Valor diárias                        24293 non-null  float64
 19  Valor passagens                      24293 non-null  float64
 20  Valor devolução                      24293 non-null  float64
 21  Valor outros gastos                  24293 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(13)
memory usage: 4.3+ MB

In [13]:
# O que fazer com essas linhas com todos gastos zerados?
# Os identificadores do processo de viagem de df_gastos_zerados constam na tabela 2026_Pagamento?
# Se não constarem na tabela pagamentos, essas linhas devem excluídas?

#lendo o arquivo 2026_Pagamento
df_pagamento = pd.read_csv('2026_Pagamento.csv', sep=';', decimal=',', encoding='latin-1')
display(df_pagamento.head(3))

,Identificador do processo de viagem,Número da Proposta (PCDP),Código do órgão superior,Nome do órgão superior,Codigo do órgão pagador,Nome do órgao pagador,Código da unidade gestora pagadora,Nome da unidade gestora pagadora,Tipo de pagamento,Valor
0,21116870,000073/26,26000.0,Ministério da Educação,26436.0,"Instituto Federal de Educação, Ciência e Tecno...",151964,INST.FED.SUL-RIO-GRANDENSE/VENANCIO AIRES,DIÁRIAS,107.83
1,21342207,000001/26,52000.0,Ministério da Defesa,52121.0,Comando do Exército,160085,ESTADO-MAIOR DO EXERCITO,PASSAGEM,5927.18
2,21346664,000002/26,52000.0,Ministério da Defesa,52121.0,Comando do Exército,160085,ESTADO-MAIOR DO EXERCITO,PASSAGEM,5927.18

In [14]:
#Checando se na tabela de pagamentos constam os Id's refrente aos registros com todoso os gastos zerados: 
#criando série dos id's de df_gastos_zerados
id_gastos_zerados = df_gastos_zerados['Identificador do processo de viagem']

df_pag_zerados = df_pagamento[
    df_pagamento["Identificador do processo de viagem"].isin(id_gastos_zerados)
]

df_pag_zerados

#Retornou um dataframe vazio. A tabela de pagamentos do Portal da Transparência só registra viagens que geraram desembolso.

Empty DataFrame
Columns: [Identificador do processo de viagem, Número da Proposta (PCDP), Código do órgão superior, Nome do órgão superior, Codigo do órgão pagador, Nome do órgao pagador, Código da unidade gestora pagadora, Nome da unidade gestora pagadora, Tipo de pagamento, Valor]
Index: []

In [15]:
# Checando os id's das duas tabelas podem ser comparados, isto é, são do mesmo tipo:
print(df_viagem["Identificador do processo de viagem"].dtype)
print(df_pagamento["Identificador do processo de viagem"].dtype)

int64
int64

## Resumo Estatístico para as colunas de valores dos gastos:

In [76]:
# Resumo estatísitco das colunas de gastos:
colunas_gastos = ["Valor diárias", "Valor passagens", "Valor devolução", "Valor outros gastos"]
print(round(df_viagem[colunas_gastos].describe(), 2))

       Valor diárias  Valor passagens  Valor devolução  Valor outros gastos
count      406083.00        406083.00        406083.00            406083.00
mean         1608.16          1274.45            16.35                17.52
std          2982.50          2938.32           248.14               157.03
min             0.00             0.00             0.00                 0.00
25%           394.14             0.00             0.00                 0.00
50%           958.86             0.00             0.00                 0.00
75%          1710.00          1908.09             0.00                 0.00
max         81175.00        171116.23         28746.23             40495.53

## Prévia de análise de viagens com a situação "Não realizada":

In [73]:
# Prévia de análise de viagens com a situação "Não realizada"
print(df_viagem["Situação"].value_counts())
print('\n')

# Filtrando não realizadas:
df_nao_realizadas = df_viagem[df_viagem["Situação"]=="Não realizada"]
print('Qtde de linhas e colunas:',df_nao_realizadas.shape)

# Percentual de viagens não realizadas que não constam quaisquer devoluções de valores:
qtd = (df_nao_realizadas['Valor devolução'] == 0).sum()
total = len(df_nao_realizadas)

print(f'Viagens não realizadas sem devolução de valor: {qtd} de {total} ({qtd/total:.1%})')

print('\n')
print("Primeiras cinco linhas de df_nao_realizadas:")
display(df_nao_realizadas.head())

Situação
Realizada        401192
Não realizada      4891
Name: count, dtype: int64


Qtde de linhas e colunas: (4891, 22)
Viagens não realizadas sem devolução de valor: 3253 de 4891 (66.5%)


Primeiras cinco linhas de df_nao_realizadas:

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
29,21420793,000001/26,Não realizada,NÃO,Sem informação,26000,Ministério da Educação,26250,Universidade Federal de Roraima,***.514.199-**,...,-1,Sem informação,2026-01-25,2026-01-31,Manaus/AM,Participar da reunião anual do PPG- Bionorte q...,0.00,3988.82,0.00,0.0
77,21470282,000009/26,Não realizada,NÃO,Sem informação,68000,Ministério de Portos e Aeroportos,62201,Agência Nacional de Aviação Civil,***.602.891-**,...,CCT-IV,Cargo Comissionado Técnico,2026-03-17,2026-03-18,Rio de Janeiro/RJ,Visita técnica ao escritório Rio de Janeiro/RJ...,888.18,584.88,888.18,0.0
78,21470770,000010/26,Não realizada,NÃO,Sem informação,68000,Ministério de Portos e Aeroportos,62201,Agência Nacional de Aviação Civil,***.497.458-**,...,CCT-V,Cargo Comissionado Técnico,2026-03-17,2026-03-18,Rio de Janeiro/RJ,Visita técnica ao escritório Rio de Janeiro/RJ...,888.18,429.23,888.18,0.0
88,21484778,000001/26,Não realizada,NÃO,Sem informação,67000,Ministério da Igualdade Racial,67000,Ministério da Igualdade Racial - Unidades com ...,***.952.726-**,...,CCX-0117,CCX-0117,2026-01-28,2026-02-01,Recife/PE,Caravana Federativa do Estado de Pernambuco.,0.00,1988.64,0.00,0.0
113,21492870,000001/26,Não realizada,NÃO,Sem informação,26000,Ministério da Educação,26284,Fundação Universidade Federal de Ciências da S...,***.440.940-**,...,-1,Sem informação,2026-05-11,2026-05-16,Curitiba/PR,XXIX CONGRESSO BRASILEIRO DE NUTRIÇÃO - CONBRA...,0.00,623.72,0.00,0.0

In [77]:
# Comparando não realizadas com a tabela 2026_Pagamento:

id_nao_realizadas = df_nao_realizadas['Identificador do processo de viagem']

df_pagto_nao_realizadas = df_pagamento[
    df_pagamento["Identificador do processo de viagem"].isin(id_nao_realizadas)
]

df_pagto_nao_realizadas.shape

(10740, 10)

In [78]:
resumo = df_pagto_nao_realizadas.groupby('Nome do órgão superior').agg(
    qtd_processos=('Identificador do processo de viagem', 'nunique'),
    qtd_pagamentos=('Identificador do processo de viagem', 'count'),
    total_pago=('Valor', 'sum'),
    media_paga=('Valor', 'mean'),
    maior_pago=('Valor', 'max')
).sort_values('total_pago', ascending=False)

In [79]:
resumo.loc['TOTAL'] = [
    df_pagto_nao_realizadas['Identificador do processo de viagem'].nunique(),
    df_pagto_nao_realizadas['Identificador do processo de viagem'].count(),
    df_pagto_nao_realizadas['Valor'].sum(),
    df_pagto_nao_realizadas['Valor'].mean(),
    df_pagto_nao_realizadas['Valor'].max()
]

resumo.sort_values('Nome do órgão superior')

,qtd_processos,qtd_pagamentos,total_pago,media_paga,maior_pago
Nome do órgão superior,,,,,
Advocacia-Geral da União,29.0,35.0,76004.16,2171.547429,7017.23
Banco Central do Brasil - Orçamento Fiscal e Seguridade Social,14.0,14.0,18427.38,1316.241429,4139.93
Controladoria-Geral da União,24.0,52.0,55328.64,1064.012308,9052.92
Ministério da Agricultura e Pecuária,102.0,245.0,496525.93,2026.636449,14125.90
"Ministério da Ciência, Tecnologia e Inovação",86.0,164.0,462096.65,2817.662500,36158.86
Ministério da Cultura,71.0,166.0,285282.08,1718.566747,5749.33
Ministério da Defesa,618.0,1238.0,2304500.51,1861.470525,68453.73
Ministério da Educação,806.0,1693.0,3460576.19,2044.049728,28625.92
Ministério da Fazenda,232.0,541.0,755196.05,1395.926155,11815.64
Ministério da Gestão e da Inovação em Serviços Públicos,757.0,1575.0,2798797.57,1777.014330,16381.58
Ministério da Integração e do Desenvolvimento Regional,51.0,105.0,191604.87,1824.808286,5319.76
Ministério da Justiça e Segurança Pública,139.0,234.0,636219.58,2718.887094,11569.59
Ministério da Pesca e Aquicultura,14.0,14.0,31459.15,2247.082143,15918.09
Ministério da Previdência Social,146.0,356.0,683262.86,1919.277697,13179.03
Ministério da Saúde,318.0,774.0,1730172.67,2235.365207,53135.96
Ministério das Cidades,14.0,15.0,22329.15,1488.610000,3646.21
Ministério das Comunicações,36.0,80.0,272122.85,3401.535625,49671.49
Ministério das Relações Exteriores,32.0,52.0,336128.79,6464.015192,31227.17
Ministério de Minas e Energia,130.0,289.0,625392.83,2163.989031,26156.49
Ministério de Portos e Aeroportos,147.0,353.0,584676.06,1656.306119,19419.22
Ministério do Desenvolvimento Agrário e Agricultura Familiar,142.0,335.0,703078.05,2098.740448,10223.31
"Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome",112.0,250.0,530239.09,2120.956360,53770.02
"Ministério do Desenvolvimento, Indústria, Comércio e Serviços",54.0,136.0,339402.23,2495.604632,20733.79
"Ministério do Empreendedorismo, da Microempresa e da Empresa de Pequeno Porte",16.0,31.0,51521.34,1661.978710,3768.83
Ministério do Esporte,14.0,31.0,84161.01,2714.871290,10610.86
Ministério do Meio Ambiente e Mudança do Clima,140.0,361.0,711762.32,1971.640776,24824.30
Ministério do Planejamento e Orçamento,39.0,82.0,185634.77,2263.838659,20116.83
Ministério do Trabalho e Emprego,82.0,168.0,315952.58,1880.670119,28746.23
Ministério do Turismo,16.0,40.0,82315.52,2057.888000,4191.40
Ministério dos Direitos Humanos e Cidadania,17.0,28.0,70067.42,2502.407857,10465.32
Ministério dos Povos Indígenas,23.0,45.0,99726.16,2216.136889,5966.09
Ministério dos Transportes,157.0,371.0,817844.99,2204.433935,31998.16
Presidência da República,67.0,94.0,223334.27,2375.896489,18048.30
Sigiloso,384.0,773.0,1740381.57,2251.463868,21551.01
TOTAL,4877.0,10740.0,21781525.29,2028.074980,68453.73